// <auto-generated />
namespace _11_RestaurantRater.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class addedratingagain : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedratingagain));
        
        string IMigrationMetadata.Id
        {
            get { return "202011092052250_added-rating-again"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
