// <auto-generated />
namespace _12_General_Store.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class addedquantitytotransaction : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedquantitytotransaction));
        
        string IMigrationMetadata.Id
        {
            get { return "202011101627144_added-quantity-to-transaction"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
